### ISSUE TITLE
breadcrumbs and the search bar should be displayed on opportunity pages

### ISSUE THREAD

**Issue by darcav1** [SciStarter/Circuit#139]
users (logged in and not) may have a hard time getting back to their prior search from an opportunity page...should the project finder be on the right side of the page along with the search bar at the top ? Do we need breadcrumbs?

**Comment by kevinripka-uiowa** [comment]
I think a 'back to search' button where a breadcrumb would be would be sufficient. Definitely not the search bar. You can start a new search in top right. 
@SciStarter - is there a way for me to only show the 'back to search' button if they came from the search page? And trigger back button on click so their search is still populated in the same state and page of results?

**Comment by kevinripka-uiowa** [comment]
This is fixed in an agreed upon way.
However @SciStarter, I can't figure out how to know if the previous page is coming from 'find'. If you look at opportunity.vue lines 39-46 you'll see I have this there, but it wants a variable called 'prevRoute' if it came from find so it can show a back button rather than normal breadcrumbs. I tried everything on https://stackoverflow.com/questions/53788975/vue-router-how-to-get-previous-page-url except the Vuex solution, since I had no idea where to do that.

**Comment by SciStarter** [comment]
Okay, I'll take care of it.
